### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by JuanDavidVelasquezSanchez** [JuanDavidVelasquezSanchez/Clase9#1]
Construir la ventana1 y hacer el formulario para ingresar la información del cliente

**Comment by ghost** [comment]
Saludos, voy a encargarme de esta funcionalidad.

**Comment by JuanDavidVelasquezSanchez** [comment]
Listo trabajo cumplido, por favor revisar el nuevo issue  para hacer ventana1.py el formulario de registro del usuario
