### ISSUE TITLE
programar el botón para buscar las preguntas de recuperación

### ISSUE THREAD

**Issue by JuanDavidVelasquezSanchez** [JuanDavidVelasquezSanchez/Clase9#6]
Validar que se  ingrese el documento del usuario al cual se le va a buscar la contraseña, validar que el documento sea un dato tipo numérico, crear la clase usuario con sus 11 propiedades, solo considerar un password, buscar las preguntas para recuperar la contraseña.

**Comment by ghost** [comment]
Me voy a encargar de este issue voy a desarrollarlo.
Pendiente de alguna sugerencia

**Comment by JuanDavidVelasquezSanchez** [comment]
listo, quedo pendiente de su primer push y pull request
